### ISSUE TITLE
Reporting bugs

### ISSUE THREAD

**Issue by ininja-ininja** [Enginette/enginette#43]
**_I have found some bugs:_**

- Cannot delete engines
- 3 generated errors when loading an enginette script to Engine Sim: **Script failed to compile**, **Error unresolved reference**, **Error unresolved reference**

**Comment by ininja-ininja** [comment]
Could it be that I need to update my engine sim (its 0.1.12.2)?

**Comment by DDev247** [comment]
Could you send the error log from ES?
I will see what the issue is about deleting engines later today too.

**Comment by DDev247** [comment]
Could you send the error log from ES?
I will see what the issue is about deleting engines later today too.

**Comment by ininja-ininja** [comment]
This is the error log
[error_log.log](https://github.com/Enginette/enginette/files/11508860/error_log.log)

**Comment by DDev247** [comment]
Could you also send the engine file too?
I forgot to ask you to send the engine 😅

**Comment by ininja-ininja** [comment]
[engine.txt](https://github.com/Enginette/enginette/files/11511576/engine.txt)

**Comment by ininja-ininja** [comment]
Had to convert it to a .txt since it can't use .mr

**Comment by DDev247** [comment]
Okay, so rod journals aren't generated. Weird. Did you forget to edit the firing order? However, even without a correct firing order, it should work.

**Comment by ininja-ininja** [comment]
I forgot to set the firing order 😆! So I set its value, but then I got this error when I generate the script:

Error occured: Traceback (most recent call last): File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async await CodeRunner( File "/lib/python311.zip/_pyodide/_base.py", line 363, in run_async coroutine = eval(self.code, globals, locals) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<exec>", line 665, in <module> File "<exec>", line 198, in generate File "<exec>", line 175, in generate_rod_journals IndexError: list assignment index out of range

**Comment by DDev247** [comment]
> I forgot to set the firing order 😆! So I set its value, but then I got this error when I generate the script:
> 
> Error occured: Traceback (most recent call last): File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async await CodeRunner( File "/lib/python311.zip/_pyodide/_base.py", line 363, in run_async coroutine = eval(self.code, globals, locals) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 665, in File "", line 198, in generate File "", line 175, in generate_rod_journals IndexError: list assignment index out of range
> 
> It does looks like there is an issue with generating rod journals in the error.

This error actually happens if the firing order is set like this: `1,2,3` instead of `0,1,2`. I added a warning in the distributor page now addressing this issue.

**Comment by ininja-ininja** [comment]
Thank you for your help!
